### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by NathanJang**
Set error to empty object before augmenting and throwing

### CODE REVIEW

**Comment by joliss** [comment]
This is about `null` and `undefined`, is it? How about just `if (err == null) err = new Error('null/undefined exception')`? Everything else should be fine.

**Comment by NathanJang** [comment]
Better?

**Comment by stefanpenner** [comment]
@joliss thoughts?

**Comment by joliss** [comment]
Landed in 541644c. Thanks!

**Pull request closed without merging**
