### PR TITLE
Expose rebuildEntry method

### PR DESCRIPTION
**Pull request by amercier**
#### Description

This PR moves the inline function `rebuildEntry` defined in `Filter#build`, and expose it as a method of `Filter` prototype.

This allow subclasses to implement `n`:`m` filters, where `m <= n`. This can now be done easily by implementing `rebuildEntry` in sub-class.

#### Example

Please consider the following example (a Sass-to-CSS compiler):

```
var minimatch = require('minimatch');

function SassCompiler(inputNode, options) {
  ...
  this.filter = '**/[^_]*.scss'; // all files except those starting with _ (Scss partials)
}

SassCompiler.prototype = Object.create(Filter.prototype);
SassCompiler.prototype.constructor = SassCompiler;

SassCompiler.prototype.rebuildEntry(relativePath) {
  if(!minimatch(relativePath, this.filter)) {
    return; // Exclude files that don't match `this.filter`
  }
  return Filter.prototype.rebuildEntry.call(this, relativePath); // Re-use filter#rebuildEntry
}

SassCompiler.prototype.processString = function(content) {
  // Sass-to-css compilation here
};
```

Note: filtering out partials (_ files) before passing it to this plugin would defeat the purpose, because those files are still being used during the Sass-to-css compilation. Therefore, they need to be in the input tree.

### CODE REVIEW

**Comment by joliss** [comment]
You can't use `Filter` for this example, because the Sass compiler processes `@import` statements, which breaks caching. The caching logic depends on `processString` being precisely 1:1.

I'm ambivalent about this PR in general, but this definitely isn't a valid use case.

**Comment by amercier** [comment]
@joliss Thanks for your answer! That make sense, I should probably use another method for my use case.

**Comment by joliss** [comment]
So, should we close this then?

**Comment by amercier** [comment]
Yes

**Pull request closed without merging**
