### PR TITLE
Use symlinks in broccoli-filter output.

### PR DESCRIPTION
**Pull request by rwjblue**
This is a bit of a smaller change to introduce symlinking initially, before the additional optimization that #11 introduces.

### CODE REVIEW

**Comment by krisselden** [comment]
@rwjblue also, having a hook to say whether you are going to mutate the content would speed up initial builds

**Comment by krisselden** [comment]
@rwjblue I see it has a canProcessFile, but the else should be a symlink https://github.com/broccolijs/broccoli-filter/blob/master/index.js#L44

**Comment by rwjblue** [comment]
@krisselden - That line is changed to symlink in this pull request.

**Comment by timmfin** [comment]
I've merged the latest with the branch if that helps anyone: https://github.com/broccolijs/broccoli-filter/compare/64631520a78bbf74ab277172aaaad559fd8542ac...timmfin:make-filter-emit-symlinks

**Comment by joliss** [comment]
I was trying to hold this off until the rebuild API lands, so that we can do some even-slicker optimizations: leaving output files in place between rebuilds. But I was a bit too optimistic on how soon the rebuild API would land (it's still evolving a bit). So, now I did what I should've done half a year ago:

Merged this and released in 0.1.14.

Thanks @rwjblue for the PR, and thanks @stefanpenner for reminding me :)

**Comment by sandstrom** [comment]
Thanks @joliss!

**Comment by stefanpenner** [comment]
@timmfin got time to submit your tests to this project? I would love to have your energy directed to this project rather then your fork.

**Comment by joliss** [comment]
I resolved conflicts in #13 and pushed them into #22. Will defer to Stef as to what he wants merged in.

**Comment by timmfin** [comment]
@stefanpenner, I was about to make a PR based off of https://github.com/broccolijs/broccoli-filter/compare/master...timmfin:add-tests, but just noticed @joliss's PR from above. I can wait until that is merged (or planned to be merged) and then rework some of my tests on top of that.

**Comment by joliss** [comment]
I took the liberty to create a PR at #23 just so we have it. Stef can pick and choose I guess, or I'll pull them in at some point in the future :)

**Pull request merged**
